server {
    listen 80;
    server_name mdm-2isy.com www.mdm-2isy.com;
    root /var/www/mdm-2isy_vf/mdm-2isy-front/dist/mdm-2isy-front/browser;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name api.mdm-2isy.com;
    root /var/www/mdm-2isy_vf/mdm-2isy-api/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
    }
}
