server {
    listen 80;
    server_name mdm-2isy.com www.mdm-2isy.com api.mdm-2isy.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name mdm-2isy.com www.mdm-2isy.com;
    root /var/www/mdm-2isy_vf/mdm-2isy-front/dist/mdm-dashboard/browser;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/mdm-2isy.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mdm-2isy.com/privkey.pem;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 443 ssl http2;
    server_name api.mdm-2isy.com;
    root /var/www/mdm-2isy_vf/mdm-2isy-api/public;
    index index.php;
    client_max_body_size 105m;

    ssl_certificate /etc/letsencrypt/live/api.mdm-2isy.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.mdm-2isy.com/privkey.pem;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header Referrer-Policy no-referrer always;

    location ~ /\. {
        deny all;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
    }
}
